api_version = "2026-04"

[[extensions]]
name = "t:name"
handle = "quantity-discount"
type = "function"
uid = "37d9f684-b180-67a1-d416-f5a8b854ddb0e359a4d5"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.lines.discounts.generate.run"
  input_query = "src/cart_lines_discounts_generate_run.graphql"
  export = "cart-lines-discounts-generate-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"
